all:
  children:
    ydb:
      hosts:
        static-node-1.ydb-cluster.com:
        static-node-2.ydb-cluster.com:
        static-node-3.ydb-cluster.com:
        static-node-4.ydb-cluster.com:
        static-node-5.ydb-cluster.com:
        static-node-6.ydb-cluster.com:
        static-node-7.ydb-cluster.com:
        static-node-8.ydb-cluster.com:

      vars:
        ansible_user: ubuntu
        #ansible_ssh_common_args: "-o ProxyJump=ubuntu@static-node-1.ydb-cluster.com"
        ansible_ssh_private_key_file: "{{ ansible_config_file | dirname + '../ydb-ssh-conn' }}"

        system_timezone: UTC
        system_ntp_servers: [time.cloudflare.com, time.google.com, ntp.ripe.net, pool.ntp.org]

        ydb_archive: "{{ ansible_config_file | dirname + '../ydbd-23.3.17-linux-amd64.tar.gz' }}"
        ydb_config: "{{ ansible_config_file | dirname + '/files/config.yaml' }}"
        ydb_tls_dir: "{{ ansible_config_file | dirname + '/files/CA/certs/2024-02-06_12-44-53' }}"

        # ydb_install_fq_connector - install fq-connector-go.
        # See https://ydb.tech/docs/ru/devops/manual/federated-queries/connector-deployment
        ydb_install_fq_connector: false

        # ydb_fq_connector_version - version of fq-connector-go we want to install.
        # This version will be taken from official repository
        # See https://github.com/ydb-platform/fq-connector-go/releases
        ydb_fq_connector_version: "v0.7.2-rc.5"

        # ydb_fq_connector_archive - path to TAR.GZ archive with binary.
        # ydb_fq_connector_archive: "{{ ansible_config_file | dirname }}/../fq-connector-go-v0.7.2-rc.5-linux-amd64.tar.gz"

        # ydb_fq_connector_binary - path to the fq-connector-go binary file.
        # ydb_fq_connector_binary: "{{ ansible_config_file | dirname }}/files/fq-connector-go"
        
        # ydb_fq_connector_config - path to fq-connector-go config. 
        # It will be placed as it is.
        ydb_fq_connector_config: "{{ ansible_config_file | dirname + '/files/fq-connector-go/config.yaml' }}"

        ydb_user: root
        ydb_cores_static: 8 
        ydb_disks:
          - name: /dev/vdb
            label: ydb_disk_1
        ydb_allow_format_drives: true
        ydb_skip_data_loss_confirmation_prompt: false
        ydb_domain: Root
        ydb_dbname: database
        ydb_pool_kind: ssd
        ydb_database_groups: 7
        ydb_cores_dynamic: 8
        ydb_dynnodes:
          - { instance: 'a', offset: 0 }
          - { instance: 'b', offset: 1 }
        ydb_brokers:
          - static-node-1.ydb-cluster.com
          - static-node-2.ydb-cluster.com
          - static-node-3.ydb-cluster.com
